"""Dodano pole reserved do modelu Desk.

Revision ID: 262ae4cdfc31
Revises: 368341c98cb0
Create Date: 2025-06-29 18:58:46.028455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262ae4cdfc31'
down_revision = '368341c98cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('reserved')

    # ### end Alembic commands ###
