"""Initial migration with named constraints

Revision ID: 368341c98cb0
Revises: 
Create Date: 2025-06-29 17:46:01.652081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368341c98cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_desk_desk_id', ['desk_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    with op.batch_alter_table('desk', schema=None) as batch_op:
        batch_op.drop_constraint('uq_desk_desk_id', type_='unique')

    # ### end Alembic commands ###
